FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .npmrc ./

# Install dependencies 
RUN npm install

# Copy the rest of the application
COPY . .

# Set environment variables for development
ENV WDS_SOCKET_PORT=3001
ENV WDS_SOCKET_HOST=localhost

# Expose port
EXPOSE 3000

# Start the development server
CMD ["npm", "start"] 