version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=${APP_ENV:-development}
      - PRODUCTION=${PRODUCTION:-false}
      - PORT=8000
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
    command: ${WEB_COMMAND:-uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload}
    depends_on:
      - redis
    volumes:
      # Mount app code for development hot reloading
      - ${MOUNT_APP:-./app:/app/app}
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker worker --loglevel=info --concurrency=${CELERY_CONCURRENCY:-2}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=${APP_ENV:-development}
      - PRODUCTION=${PRODUCTION:-false}
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
    depends_on:
      - redis
    volumes:
      # Mount app code for development hot reloading
      - ${MOUNT_APP:-./app:/app/app}
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 