[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "python39Packages.pip"]
nodeVersion = "18"
pythonVersion = "3.9"

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p ../app/static",
  "cp -r build/* ../app/static/",
  "cd .."
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 